### ISSUE TITLE
Followup Messages are not coming in Android App

### ISSUE THREAD

**Issue by vittalpai** [IBM-Bluemix/serverless-followupapp-android#1]
Every time when user submits feedback, the follow up push notification is not coming.

I have observed following error in Openwhisk monitor.

 
![image](https://user-images.githubusercontent.com/1935263/34811078-150bb52a-f6c5-11e7-8f12-4f6245eca0ab.png)

**Comment by VidyasagarMSC** [comment]
@vittalpai Based on our interactions, this is resolved. So closing the issue.
